version: '3.9'

services:
  server:
    container_name: api
    build:
      context: .
    environment:
      NODE_ENV: development
    ports: 
      - 3333:3333
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:9.2.0
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      - ./src/infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # working_dir: /var/lib/mysql
    expose:
      - 3306
    # healthcheck:
    #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #     timeout: 20s
    #     retries: 10
    environment:
      MYSQL_DATABASE: appointments
      MYSQL_USER: user_appointments
      MYSQL_PASSWORD: 12wqer43
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    # command: >
    #         mysqld
    #             --lower_case_table_names=1 --skip-ssl
    #             --character_set_server=utf8mb4
    #             --collation-server=utf8mb4_unicode_ci
    #             --explicit_defaults_for_timestamp
    #             --default-authentication-plugin=mysql_native_password
volumes:
  db_data:
